### ISSUE TITLE
Add documentation for multi-dot paths

### ISSUE THREAD

**Issue by kit494way** [nushell/nushell.github.io#1225]
Multi-dots (e.g. `...`) is recognized as ancestor directory as follows

```nu
❯ pwd
/tmp/one/two/three

❯ do { cd ..; pwd }
/tmp/one/two

❯ do { cd ...; pwd }
/tmp/one

❯ do { cd ....; pwd }
/tmp
```

But this is only mentioned briefly in a release [note](https://github.com/nushell/nushell.github.io/blob/0d45d82de1d2ce2a7c50e2738eb505cd18967ff6/blog/2020-04-21-nushell_0_13_0.md?plain=1#L47) and in spread operator [section](https://github.com/nushell/nushell.github.io/blob/0d45d82de1d2ce2a7c50e2738eb505cd18967ff6/book/operators.md?plain=1#L194) of the documentation.

I think it would be helpful to create a dedicated section on the page of [moving around](https://github.com/nushell/nushell.github.io/blob/main/book/moving_around.md), and make links to the section from pages of `cd` and `mv` etc.

**Comment by fdncred** [comment]
Sounds good. Thanks for the suggestion.

**Comment by NotTheDr01ds** [comment]
Unfortunately we really can't update the `cd` and `mv` command documentation itself to point to *"Moving around"*, since those are generated based on the built-in command's help.  However, I've updated the *"Moving around"* doc itself, and I'll make some tweaks to the `cd` help, at least.  Might add an example for `mv`, `cp` and others showing this usage as well.
