### ISSUE TITLE
Style Guide - 2 space or 4 space indentation?

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell.github.io#1602]
The [Best Practices](https://nushell.sh/book/style_guide.html) (a.k.a. Style Guide) chapter of the Nushell Book includes recommendations for Nushell code that is contributed to official Nushell repositories (e.g., [nu_scripts](/nushell/nu_scripts).

As mentioned in the first paragraph:

> as for now it is still work in progress and subject to change. We welcome discussion and contributions.

On the weekly call today, we agreed that we need to more actively reach out for community feedback on certain areas, with a Nushell issue (such as this one) being decided on as the way the community can "vote" most easily.

Please vote on your "Indentation" preference below by selecting the Thumbs-Up emoji on your preferred option below.

![image](https://github.com/user-attachments/assets/70cf4a3f-9da4-4ba8-bdc7-d03f76f2b917)

Comments are welcome as well.

**Comment by NotTheDr01ds** [comment]
2-space indentation:

```nu
export def "list merge" []: list<record> -> record {
  let list = $in
  mut result = {}
  for $obj in $list {
    $result = ($result | merge $obj)
  }
  $result
}
```

**Comment by NotTheDr01ds** [comment]
4-space indentation:

```nu
export def "list merge" []: list<record> -> record {
    let list = $in
    mut result = {}
    for $obj in $list {
        $result = ($result | merge $obj)
    }
    $result
}
```

**Comment by NotTheDr01ds** [comment]
1-tab (`\t`) for indentation

**Comment by dyskos** [comment]
I have always advocated for tabs because spaces are less useful in nearly every case otherwise.

Here are my arguments in support of this claim:
- Their handling and behaviour are not portably guaranteed across various editors
- They unnecessarily use more storage
- The "2 vs 4 vs 8" argument becomes moot with tabs because a person's choice of editor and its configuration will display the appropriate tab-size accordingly

One argument that I'm aware of in support of spaces is for EOL comment alignment. In my opinion, EOL alignment is a separate issue to indentation, as tabs can be used in tandem with spaces where tabs are used for indentation, and spaces are used for EOL comment alignment. This is what Go does, for example.

And to clarify, a common style can still be recommended where EOL alignment assumes a 4-width tab indentation and formatters will align EOL comments accordingly. I think EOL comment alignment is already a messy practice and I tend to avoid this in my code anyhow.

In my opinion, spaces are just about always a net loss for everyone.

**Comment by sholderbach** [comment]
To throw another curveball in here:

Should we consider different indentation rules for block indentation vs. pipeline continuation?

```nushell
def foo [] {
    bar |
      baz
}
```

**Comment by NotTheDr01ds** [comment]
@sholderbach Personally, I started out with the "pipe at the end of the line", but then I was under the impression (from `nufmt` comments, I believe) that we'd settled on the "wall of pipes" form for it:

```nushell
def foo [] {
    bar
    | baz
    | cat
```

I've come to see that as much more readable, since you don't have to look for "magic indentation" or pipes at different column positions at the end of each line.

I had put the "wall of pipes" in the style guide update based on `nufmt` notes.

**Comment by sholderbach** [comment]
Wall of pipes may be aesthetically better but rather impractical for REPL use as you have to mentally switch between using submitting enter or a binding for inserting a new line without submitting. With trailing operator style you can keep going in REPL as if you were in a file in the editor and are closer to the subtle rules we have in the syntax for command call rules.
