### ISSUE TITLE
Website doesn't work over HTTPS without www subdomain

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell.github.io#294]
If you try to access the Nushell site over HTTPS without the www subdomain it times out:

https://nushell.sh
https://nushell.sh/book/

Not a huge deal but there's probably some way to fix this via DNS settings.

**Comment by fdncred** [comment]
I've noticed this too, as sometimes I would just put in nushell.sh and it wouldn't work. I'm not sure how to change this myself.

**Comment by TyPR124** [comment]
This looks like an issue with github pages to me: https://github.community/t/does-github-pages-support-https-for-www-and-subdomains/10360/8

Unfortunate, but it doesn't seem like github is interested in fixing this. A suggestion from that thread is to use Cloudflare as a front-end.

For what it's worth, I recently changed [stdrs.dev](https://stdrs.dev) to use Cloudflare and I have no issues (certificate or otherwise) with either stdrs.dev or www.stdrs.dev so far.

Cloudflare is free (they do have paid features but nothing you'd require for this), and provides some really nice insights into traffic. That said, the main drawback for me is that they force you to use their nameservers for your domain. Not really a big deal, just something I find annoying.

It is not a difficult thing to do, but I wouldn't mind providing some help in this area if you do want to make any changes. It looks like nushell.sh is registered with Namecheap, so to start with you'd need to register with Cloudflare and have your login info for Namecheap at the ready.

**Comment by DannyJJK** [comment]
I noticed this recently because I started using an RSS feed reader and I have all my URLs listed in a file. I try to keep the URLs tidy so I remove `www.`, which on some websites will end up redirecting to the `www.` anyway, but I noticed that the Nushell RSS feed wasn't resolving. I worked out this was because I was missing the `www.`, but Nushell is the only website in my list that requires `www.` to work. It's not the end of the world, but it looks strange as it's the odd one out.

**Comment by LingMan** [comment]
Just wanted to try out nushell. On startup it shows a banner with some basic info, including a link to the documentation at `http://nushell.sh`. Opening that shows an error message since my browser runs in https-only mode. Urgh, so I ended up here.

Looking at the current DNS records and at [Github's documentation on the matter](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain), you need to go to your DNS provider and setup `A` records pointing `nushell.sh` to the Github Pages IP addresses:
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
(Delete the currently existing `A` record pointing to `192.64.119.90`.)

Ideally you'd also create `AAAA` records so the growing number of users who only have IPv6 connectivity can actually reach the site:
```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```
If my reading of the docs is correct, everything else should fall in place by itself. Maybe increase the TTL once you've confirmed that everything works correctly from the current 233/1800 to 3600. No need to invalidate the cache entries every four minutes.

**Comment by jntrnr** [comment]
@LingMan - I've updated them the IP address. Once that seems to have fixed it I can update the TTL also

**Comment by rgwood** [comment]
It's fixed now for me. Thanks @jntrnr and @LingMan!
