### ISSUE TITLE
Specify type of Range

### ISSUE THREAD

**Issue by adzubla** [nushell/nushell.github.io#404]
In https://www.nushell.sh/book/types_of_data.html#ranges

Replace "A range is a way of expressing a sequence of values from start to finish."

To "A range is a way of expressing a sequence of INTEGER values from start to finish."

**Comment by fdncred** [comment]
There are things like this too.
`for $x in 0x61..0x7a { $x }`
`for $x in 0x61..0x7a { char -i $x }`
`for $x in 0b01..0b100 { $x }`
`for $x in 0o1..0x10 { $x }`

but you're right that we currently can't do `for x in a..z`. this is because `a..z` theoretically could be a filename. but we may be able to do `for x in "a".."z"` or something along those lines. I'd like to have some way to iterate letters other than the 2nd example above.

**Comment by TWSiO** [comment]
Ranges also work with float values so we could broaden this to either

- "... a sequence of NUMBERS..."
- "... a sequence of INTEGER OR FLOAT values..."

Also, perhaps we can add a tip in that section suggesting how they can use number ranges to get ranges of other types like with `for $x in 0x61..0x7a { char -i $x }`.

**Comment by TWSiO** [comment]
Actually, they don't work with binary values so it might be better to go with "INTEGER OR FLOAT" values just to avoid confusion.
