### ISSUE TITLE
Book PDF

### ISSUE THREAD

**Issue by josephburnett** [nushell/nushell.github.io#658]
I want to read the book! But it's hard for me to read on a computer (I keep getting distracted). I would really like to download a rendered PDF copy onto my reader. However there doesn't appear to be one! Can you help me out?

**Comment by kubouch** [comment]
If I remember correctly, @hustcer made an ebook a while ago.

**Comment by rgwood** [comment]
Yeah I think the PDF+ePub versions are here: https://github.com/hustcer/open-books

Might be a little out of date, looks like they haven't been updated in a while.

**Comment by josephburnett** [comment]
Well a little out of date is better than nothing. Thanks!

**Comment by kubouch** [comment]
You could reach out to hustcer and ask how he did it, it shouldn't be too hard to generate.

**Comment by hustcer** [comment]
I will update the latest PDF book around the next Nu release

**Comment by josephburnett** [comment]
Thanks!

Might be worth adding a Makefile (or nushell script) to regenerate and upload to Github releases. Then you can just reference the latest release in the website.

**Comment by hustcer** [comment]
It's sad that I can't create a PDF book anymore on my mac, It just didn't work well as before. What was worse, there is no useful error message output, that's why I haven't update the book for quite a long time.
It's quite easy to create a epub book, but quite difficult to create an pdf version.

**Comment by hustcer** [comment]
It has been really a long time since my last updating nushell ebooks, that due to the following reasons:
1. Nushell docs and commands have changed a lot
2. My enviroment that create pdf files was corruptted and didn’t work anymore

Luckily, I have spent about 3 days to make all that work again, and I have just created the nushell ebooks for v0.71 here, you can download them as you like:
https://github.com/hustcer/open-books/raw/main/Nushell-Book.epub
https://github.com/hustcer/open-books/raw/main/Nushell-Book.pdf

**Comment by josephburnett** [comment]
Thanks @hustcer for getting that working again! If you provide me with some idea about how to generated those, perhaps I could submit a pull request to have them generated regularly as part of the project.

**Comment by hustcer** [comment]
@josephburnett I'm using https://github.com/lise-henry/crowbook to create epub and pdf books. Just read this online doc: https://lise-henry.github.io/crowbook/book/book.html and you may know what to do
